services:
  timescaledb:
    # Latest stable version, based on PostgreSQL 17
    image: timescale/timescaledb:2.26.3-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-net

networks:
  local-net:
    external: true